version: '3.5'
services:
################################################################################
  nginx:
    container_name: nginx
    image: nginx-php-fpm:1.0
    restart: always
    ports:
      - 8080:80
    volumes:
      - web:/var/www/html:rw
      - log:/var/log/nginx:rw
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
################################################################################
  mariadb:
    container_name: mariadb
    image: mariadb:10.1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=php_sample_root_password
      - MYSQL_DATABASE=php_sample_db
      - MYSQL_USER=php_sample_user
      - MYSQL_PASSWORD=php_sample_password
    volumes:
      - database:/var/lib/mysql/estiam:rw
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
################################################################################
volumes:
  web:
  log:
database: